news/urls.py
from django.urls import path
from .views import home, articoloDetailView,listaArticoli,queryBase,giornalisti_list_api,giornalista_api,articolo_list_api,articolo_api

app_name="news"

urlpatterns=[
    path('', home, name="homeview"),
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli_giornalista"),
    path("lista_articoli/", listaArticoli, name="lista_articoli"),
    path("query_base/", queryBase, name="query_base"),


    path('', home, name="homeview"),
    path("giornalisti_list_api/", giornalisti_list_api, name="giornalisti_list_api"),
    path("giornalista_api/<int:pk>", giornalista_api, name="giornalista_api"),
    path("articolo_list_api/", articolo_list_api, name="articolo_list_api"),
    path("articolo_api/<int:pk>", articolo_api, name="articolo_api")
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista,chisiamo,variabili,index

app_name="prima_app"
urlpatterns=[
    path('homepage', homepage, name='homepage'),
    path('welcome', welcome, name='welcome'),
    path('lista', lista, name='lista'),
    path('chisiamo', chisiamo, name='chisiamo'),
    path('variabili', variabili, name='variabili'),
    path('index', index, name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/', include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/', include("seconda_app.urls",namespace="seconda_app")),
    path('prova_pratica_1/', include("prova_pratica_1.urls",namespace="prova_pratica_1")),
    path('news/', include("news.urls",namespace="news")),
    path('voti/', include("voti.urls",namespace="voti")),
    path('',index,name="index")
]

prova_pratica_1/urls.py
from django.urls import path
from prova_pratica_1.views import *

app_name="prova_pratica_1"
urlpatterns=[
    path('indexP', indexP, name='indexP'),
    path('somma', somma, name='somma'),
    path('media', media, name='media'),
    path('voti', voti, name='voti'),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if,if_else_elif,es_for,index_seconda

app_name="seconda_app"

urlpatterns = [
    path('es_if', es_if, name='es_if'),
    path('if_else_elif', if_else_elif, name='if_else_elif'),
    path('es_for', es_for, name='es_for'),
    path('', index_seconda, name='index_seconda'),
]

voti/urls.py
from django.urls import path
from voti.views import lista_materie,voti_studenti,media_studenti,max_min_voti

app_name="voti"

urlpatterns = [
    path('lista_materie', lista_materie, name='lista_materie'),
    path('voti_studenti', voti_studenti, name='voti_studenti'),
    path('media_studenti', media_studenti, name='media_studenti'),
    path('max_min_voti', max_min_voti, name='max_min_voti'),
]

primo_progetto/views.py
from django.shortcuts import render

def index(request):
    return render(request,"index_root.html")

primo_progetto/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Primo progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Prima app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Home</a>
                  <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
                  <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                  <a class="dropdown-item" href="{% url 'prima_app:chisiamo'%}">Chi siamo</a>
                  <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Seconda app
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">If</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">Else_elif</a>
                  <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">For</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Prova Pratica 1
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:indexP'%}">IndexP</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:somma'%}">Somma</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:media'%}">Media</a>
                  <a class="dropdown-item" href="{% url 'prova_pratica_1:voti'%}">Voti</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Voti
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'voti:lista_materie'%}">Lista delle materie</a>
                  <a class="dropdown-item" href="{% url 'voti:voti_studenti'%}">Voti degli studenti</a>
                  <a class="dropdown-item" href="{% url 'voti:media_studenti'%}">Media degli studenti</a>
                  <a class="dropdown-item" href="{% url 'voti:max_min_voti'%}">Massimo e minimo</a>
                </div>
              </li>
          </ul>
        </div>
      </nav>
      <div class="container my-4">
        <!--servirà per inserire i contenuti della pagina-->
        {%block content%}
        {%endblock content%}
        <!--servirà per inserire il codice javascript-->
        {%block script%}
        {%endblock script%}
      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

primo_progetto/templates/index_root.html
{% extends "base.html"%}

{%block title%} {{block.super}} | Index root {%endblock title%}

{%block content%}
    <h1>PRIMO PROGETTO</h1>
    
    <ol>
        <li><a href="/admin">Pannello admin</a></li>
        <li><a href=" {% url 'prima_app:index'%} ">Index prima app</a></li>
        <li><a href=" {% url 'seconda_app:index_seconda'%} ">Index seconda app</a></li>
        <li><a>.....</a></li>
    </ol>
{% endblock content%}